name: production

on:
  push:
    branches: [main]

jobs:
  apply_github_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Apply Github infrastructure
        env:
          TF_VAR_ludicrum_token: ${{ secrets.LUDICRUM_TOKEN }}
        run: bash common/infrastructure/jobs/apply_github_infrastructure.sh
